[[CURRENCIES]]
code="{Paper}"
issuer="{GDS7GLWWA3PJMQF2Y57BIVYYVKPG46USOUHDEBVTV7VG7CUXRV5CVIP2}"
display_decimals={11}
name="{Paper}"
desc="{description of asset}"
conditions="{conditions for usage and distributions of the asset}"
image="{https://raw.githubusercontent.com/papertoken/paper/master/paperlogo.png}"
